### ISSUE TITLE
对 /network/iocp/tcpsocket.cpp中一处代码的疑问

### ISSUE THREAD

**Issue by forl** [zsummer/zsummer#5]
源文件 /network/iocp/tcpsocket.cpp 里408-412行有这样的代码：

``` cpp
        if (m_nNeedDelete != 0)
        {
            DestroyTcpSocket(this);
        }
        m_nNeedDelete = 0;
```

在类成员函数中调用  `delete this` 之后再访问类成员变量应该是有问题的。

**Comment by zsummer** [comment]
是的. 这个地方有问题.      修掉这个bug我需要重新review这套代码并且测试.   zsummer我已经停止维护很久了  大约已经有两年没维护过了 暂时不想再动这套代码,  而且在未来 这套代码对我来说也没什么使用价值了.  
现在维护的是log4z-proto4z->zsummerX->breeze这一套开源, 在我公司和其他公司的项目里都在用. 
非常感谢关注我的开源.!

**Comment by forl** [comment]
好的，谢谢回复。
