### ISSUE TITLE
使用浏览器测试server疑惑

### ISSUE THREAD

**Issue by molixiaoge** [zsummer/zsummer#6]
浏览器访问server port时候，每次client OnRecv recvlen长度只有2!!

**Comment by zsummer** [comment]
zsummer的示例代码中使用的是二进制协议 2字节协议包长.  你应该是用浏览器测试的这个吧.  
zsummerX的frame层有HTTP协议的包装. 可以支持浏览器的.   不如换下zsummerX看看.   zsummer已经两年没更新了 .

**Comment by molixiaoge** [comment]
恩 我试下x

**Comment by molixiaoge** [comment]
提点建议, 一:接口设计不合理 比如 cclient::onclose方法里面delete this,这样.
               二:cclient::initsocket 调用dorecv 传的长度只有2 ,这样收包性能很差.

**Comment by zsummer** [comment]
嗯 那个是测试例子.  意思是  可以做到delete this.  但实际使用么 还是要管理起来的. 
dorecv在zsummerx中是一个functional的回调接口 有点像委托,  然后让用户自己去定义如何分包解包, 然后提供了默认的方案(使用proto4z).  比zsummer的好很多.

**Comment by molixiaoge** [comment]
c++ 11有点超前了,暂时不考虑,有时间自己写个跨平台的网络库,感觉第三方不太好用.

**Comment by molixiaoge** [comment]
对了,求推荐windows下高性能的http库.

**Comment by zsummer** [comment]
https://github.com/ipkn/crow
这个也是C++11的 而且依赖boost.
